---
- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_root }}"

- name: Install Python interpreters
  shell: >-
    export PATH="{{ pyenv_root }}/bin:$PATH" &&
    eval "$(pyenv init -)" &&
    pyenv install {{item}}
  args:
    creates: "{{ pyenv_root }}/versions/{{item}}/bin/python"
  with_items:
    - 3.8.2

- name: Create virtualenvs dir
  file:
    path: "{{virtualenv_root}}"
    state: directory

- name: manually create venv for neovim
  command:
    cmd: python3 -m venv {{virtualenv_root}}/ntp ntp

